version: "2"
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
  api:
    build: './api'
    container_name: api
    restart: always
    ports:
      - "3500:3500"
    depends_on:
      - mongodb
    links:
      - mongodb
  client:
    build: './client'
    container_name: client
    restart: always
    depends_on:
      - api
    ports:
      - "3000:3000"
